import React, { useRef, useEffect, useState } from 'react';
import jsPDF from 'jspdf';
import { useLocation, useNavigate } from 'react-router-dom';
import { EventRecord } from './EventTable';

interface EditorProps {
    event: EventRecord;
    editLog: string[];
    setEditLog: React.Dispatch<React.SetStateAction<string[]>>;
}

const ImageEditor: React.FC<EditorProps> = ({ event, editLog, setEditLog }) => {
    // Professional PDF download from image editor
    const handleDownloadPDF = () => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
        // Header
        doc.setFillColor('#1e293b');
        doc.rect(0, 0, doc.internal.pageSize.getWidth(), 60, 'F');
        doc.setTextColor('#38bdf8');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(28);
        doc.text('Event Report', 40, 40);
        // Event image
        const imgData = canvas.toDataURL('image/png');
        doc.addImage(imgData, 'PNG', 40, 80, 320, 214, undefined, 'FAST');
        // Event details table
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(14);
        doc.setTextColor('#222');
        const details = [
            ['Classification', event.classification],
            ['Object ID', event.objectId],
            ['Date', new Date(event.timestamp).toLocaleString()],
            ['Score', `${event.confidence}%`],
            ['Description', event.details || ''],
        ];
        let y = 80;
        details.forEach(([label, value], i) => {
            doc.setFont('helvetica', 'bold');
            doc.setTextColor('#0ea5e9');
            doc.text(label + ':', 400, y + 30 * i);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor('#222');
            doc.text(String(value), 520, y + 30 * i);
        });
        // Footer
        doc.setDrawColor('#38bdf8');
        doc.line(40, 320, doc.internal.pageSize.getWidth() - 40, 320);
        doc.setFontSize(10);
        doc.setTextColor('#888');
        doc.text('Generated by Miltaire Event System', 40, 340);
        doc.save('event-report.pdf');
    };
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const [drawing, setDrawing] = useState(false);
    const [tool, setTool] = useState<'pen' | 'rect' | 'ellipse' | 'text'>('pen');
    const [color, setColor] = useState('#ff0000');
    const [text, setText] = useState('');
    const [shapes, setShapes] = useState<any[]>([]);
    const [start, setStart] = useState<{ x: number, y: number } | null>(null);
    const [currentShape, setCurrentShape] = useState<any>(null);

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const ctx = canvas.getContext('2d');
        if (!ctx) return;
        const img = new window.Image();
        img.crossOrigin = 'anonymous';
        img.src = event.fullImageUrl || event.snapshotUrl;
        img.onload = () => {
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
            shapes.forEach(shape => drawShape(ctx, shape));
            if (currentShape) drawShape(ctx, currentShape);
        };
    }, [event, shapes, currentShape]);

    const drawShape = (ctx: CanvasRenderingContext2D, shape: any) => {
        ctx.save();
        ctx.strokeStyle = shape.color;
        ctx.fillStyle = shape.color;
        ctx.lineWidth = 2;
        if (shape.type === 'pen') {
            ctx.beginPath();
            ctx.moveTo(shape.points[0].x, shape.points[0].y);
            shape.points.forEach((pt: any) => ctx.lineTo(pt.x, pt.y));
            ctx.stroke();
        } else if (shape.type === 'rect') {
            ctx.strokeRect(shape.x, shape.y, shape.w, shape.h);
        } else if (shape.type === 'ellipse') {
            ctx.beginPath();
            ctx.ellipse(shape.x + shape.w / 2, shape.y + shape.h / 2, Math.abs(shape.w / 2), Math.abs(shape.h / 2), 0, 0, 2 * Math.PI);
            ctx.stroke();
        } else if (shape.type === 'text') {
            ctx.font = '20px Arial';
            ctx.fillText(shape.text, shape.x, shape.y);
        }
        ctx.restore();
    };

    const handleMouseDown = (e: React.MouseEvent) => {
        const rect = (e.target as HTMLCanvasElement).getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        setDrawing(true);
        setStart({ x, y });
        if (tool === 'pen') {
            setCurrentShape({ type: 'pen', color, points: [{ x, y }] });
            setEditLog(log => [...log, `Started pen at (${x.toFixed(0)}, ${y.toFixed(0)}) with color ${color}`]);
        } else if (tool === 'text') {
            setShapes([...shapes, { type: 'text', color, x, y, text }]);
            setEditLog(log => [...log, `Added text '${text}' at (${x.toFixed(0)}, ${y.toFixed(0)}) with color ${color}`]);
            setText('');
            setDrawing(false);
        }
    };

    const handleMouseMove = (e: React.MouseEvent) => {
        if (!drawing || !start) return;
        const rect = (e.target as HTMLCanvasElement).getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        if (tool === 'pen') {
            setCurrentShape((prev: any) => ({ ...prev, points: [...prev.points, { x, y }] }));
        } else if (tool === 'rect') {
            setCurrentShape({ type: 'rect', color, x: start.x, y: start.y, w: x - start.x, h: y - start.y });
            setEditLog(log => log.length && log[log.length - 1].startsWith('Drawing rect') ? log.slice(0, -1).concat([`Drawing rect from (${start.x.toFixed(0)}, ${start.y.toFixed(0)}) to (${x.toFixed(0)}, ${y.toFixed(0)}) with color ${color}`]) : log.concat([`Drawing rect from (${start.x.toFixed(0)}, ${start.y.toFixed(0)}) to (${x.toFixed(0)}, ${y.toFixed(0)}) with color ${color}`]));
        } else if (tool === 'ellipse') {
            setCurrentShape({ type: 'ellipse', color, x: start.x, y: start.y, w: x - start.x, h: y - start.y });
            setEditLog(log => log.length && log[log.length - 1].startsWith('Drawing ellipse') ? log.slice(0, -1).concat([`Drawing ellipse from (${start.x.toFixed(0)}, ${start.y.toFixed(0)}) to (${x.toFixed(0)}, ${y.toFixed(0)}) with color ${color}`]) : log.concat([`Drawing ellipse from (${start.x.toFixed(0)}, ${start.y.toFixed(0)}) to (${x.toFixed(0)}, ${y.toFixed(0)}) with color ${color}`]));
        }
    };

    const handleMouseUp = () => {
        if (currentShape) {
            setShapes([...shapes, currentShape]);
            if (currentShape.type === 'rect') {
                setEditLog(log => [...log, `Finished rect at (${currentShape.x.toFixed(0)}, ${currentShape.y.toFixed(0)}) size (${currentShape.w.toFixed(0)}, ${currentShape.h.toFixed(0)}) color ${currentShape.color}`]);
            } else if (currentShape.type === 'ellipse') {
                setEditLog(log => [...log, `Finished ellipse at (${currentShape.x.toFixed(0)}, ${currentShape.y.toFixed(0)}) size (${currentShape.w.toFixed(0)}, ${currentShape.h.toFixed(0)}) color ${currentShape.color}`]);
            } else if (currentShape.type === 'pen') {
                setEditLog(log => [...log, `Finished pen stroke with ${currentShape.points.length} points color ${currentShape.color}`]);
            }
        }
        setCurrentShape(null);
        setDrawing(false);
        setStart(null);
    };

    const handleSave = () => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const url = canvas.toDataURL('image/png');
        const a = document.createElement('a');
        a.href = url;
        a.download = 'edited-image.png';
        a.click();
        setEditLog(log => [...log, 'Saved image as PNG']);
    };

    return (
        <div className="flex flex-col items-center gap-4 w-full">
            <div className="flex flex-wrap gap-2 mb-3 items-center justify-center">
                <button
                    className={`px-3 py-1 rounded font-semibold border transition focus:outline-none focus:ring-2 focus:ring-blue-400 shadow-sm hover:bg-blue-600 hover:text-white ${tool === 'pen' ? 'bg-blue-500 text-white border-blue-600' : 'bg-gray-700 text-gray-200 border-gray-600'}`}
                    title="Freehand Pen Tool"
                    onClick={() => setTool('pen')}
                >
                    Pen
                </button>
                <button
                    className={`px-3 py-1 rounded font-semibold border transition focus:outline-none focus:ring-2 focus:ring-blue-400 shadow-sm hover:bg-blue-600 hover:text-white ${tool === 'rect' ? 'bg-blue-500 text-white border-blue-600' : 'bg-gray-700 text-gray-200 border-gray-600'}`}
                    title="Draw Rectangle"
                    onClick={() => setTool('rect')}
                >
                    ▭ Rect
                </button>
                <button
                    className={`px-3 py-1 rounded font-semibold border transition focus:outline-none focus:ring-2 focus:ring-blue-400 shadow-sm hover:bg-blue-600 hover:text-white ${tool === 'ellipse' ? 'bg-blue-500 text-white border-blue-600' : 'bg-gray-700 text-gray-200 border-gray-600'}`}
                    title="Draw Ellipse"
                    onClick={() => setTool('ellipse')}
                >
                    ◯ Ellipse
                </button>
                <button
                    className={`px-3 py-1 rounded font-semibold border transition focus:outline-none focus:ring-2 focus:ring-blue-400 shadow-sm hover:bg-blue-600 hover:text-white ${tool === 'text' ? 'bg-blue-500 text-white border-blue-600' : 'bg-gray-700 text-gray-200 border-gray-600'}`}
                    title="Add Text"
                    onClick={() => setTool('text')}
                >
                    🅣 Text
                </button>
                <label className="flex items-center gap-1 text-gray-300 font-medium ml-2">
                    <span>Color:</span>
                    <input type="color" value={color} onChange={e => setColor(e.target.value)} className="w-7 h-7 border-2 border-gray-400 rounded cursor-pointer" />
                </label>
                {tool === 'text' && (
                    <input
                        type="text"
                        value={text}
                        onChange={e => setText(e.target.value)}
                        placeholder="Enter text"
                        className="ml-2 px-2 py-1 rounded border border-gray-500 bg-gray-900 text-white focus:outline-none focus:ring-2 focus:ring-blue-400"
                    />
                )}
                <button
                    onClick={handleSave}
                    className="ml-2 px-3 py-1 rounded font-semibold border border-green-600 bg-green-500 text-white shadow-sm hover:bg-green-600 transition focus:outline-none focus:ring-2 focus:ring-green-400"
                    title="Save as PNG"
                >
                    Save
                </button>
                <button
                    onClick={() => {
                        setShapes(shapes.slice(0, -1));
                        setEditLog(log => [...log, 'Undo last shape']);
                    }}
                    className="ml-2 px-3 py-1 rounded font-semibold border border-yellow-600 bg-yellow-400 text-gray-900 shadow-sm hover:bg-yellow-500 transition focus:outline-none focus:ring-2 focus:ring-yellow-300"
                    title="Undo last shape"
                    disabled={shapes.length === 0}
                >
                    ↩ Undo
                </button>
                <button
                    onClick={() => {
                        setShapes([]);
                        setEditLog(log => [...log, 'Cleared all shapes']);
                    }}
                    className="ml-2 px-3 py-1 rounded font-semibold border border-red-600 bg-red-500 text-white shadow-sm hover:bg-red-600 transition focus:outline-none focus:ring-2 focus:ring-red-400"
                    title="Clear all shapes"
                    disabled={shapes.length === 0}
                >
                    Clear
                </button>
            </div>
            <div className="w-full flex flex-col items-center">
                <canvas
                    ref={canvasRef}
                    width={900}
                    height={600}
                    className="border-2 border-gray-500 rounded-lg bg-gray-900 shadow-lg cursor-crosshair w-[900px] h-[600px] max-w-full max-h-[80vh]"
                    style={{ cursor: tool === 'text' ? 'text' : 'crosshair' }}
                    onMouseDown={handleMouseDown}
                    onMouseMove={handleMouseMove}
                    onMouseUp={handleMouseUp}
                    onMouseLeave={handleMouseUp}
                />
                <div className="mt-2 w-full flex flex-wrap gap-2 items-center justify-center">
                    <span className="text-xs text-gray-400">Shapes: {shapes.length}</span>
                    {shapes.length > 0 && (
                        <span className="text-xs text-gray-500">(Undo/Clear to manage)</span>
                    )}
                    <button
                        onClick={handleDownloadPDF}
                        className="ml-2 px-3 py-1 rounded font-semibold border border-blue-600 bg-blue-500 text-white shadow-sm hover:bg-blue-600 transition focus:outline-none focus:ring-2 focus:ring-blue-400"
                        title="Download Professional PDF Report"
                    >
                        Download PDF Report
                    </button>
                </div>
            </div>
            <div className="w-full flex flex-wrap gap-2 items-center justify-center mt-2">
                <span className="text-xs text-gray-400">Tip: Use Pen for freehand, Rect/Ellipse for shapes, Text for annotations. Change color as needed. Save to download your edited image.</span>
                <label className="block w-full text-left text-gray-300 font-medium mt-2">Edit Log:</label>
                <textarea
                    className="w-full min-h-[80px] px-2 py-1 rounded border border-gray-500 bg-gray-900 text-gray-200 text-xs font-mono focus:outline-none focus:ring-2 focus:ring-blue-400"
                    value={editLog.join('\n')}
                    readOnly
                />
            </div>
        </div>
    );
};


const EventDetailPage: React.FC = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const event = (location.state as { event: EventRecord })?.event;
    const [description, setDescription] = useState(event?.details || '');
    const [editLog, setEditLog] = useState<string[]>([]);
    // const imageEditorRef = useRef<HTMLCanvasElement>(null);


    if (!event) return <div className="p-8 text-red-500">No event data provided.</div>;
    return (
        <div className="fixed inset-0 bg-gray-900 flex flex-col min-h-screen min-w-full z-50 overflow-auto">
            <div className="flex items-center justify-between p-6 border-b border-gray-800 bg-gray-900">
                <button className="px-4 py-2 bg-gray-700 text-white rounded hover:bg-gray-600 transition font-semibold tracking-wide" onClick={() => navigate(-1)}>
                    ← Back
                </button>
                <h2 className="text-4xl font-extrabold text-white font-sans tracking-tight drop-shadow-lg">
                    Event Detail <span className="text-blue-400">& Image Editor</span>
                </h2>
            </div>
            <div className="flex flex-col md:flex-row flex-1 gap-8 p-8">
                <div className="flex-1 space-y-4 max-w-md">
                    <div>
                        <label className="block text-gray-300 font-medium mb-1">Classification</label>
                        <div className="px-3 py-2 bg-gray-800 rounded text-white">{event.classification}</div>
                    </div>
                    <div>
                        <label className="block text-gray-300 font-medium mb-1">Object ID</label>
                        <div className="px-3 py-2 bg-gray-800 rounded text-white">{event.objectId}</div>
                    </div>
                    <div>
                        <label className="block text-gray-300 font-medium mb-1">Date</label>
                        <div className="px-3 py-2 bg-gray-800 rounded text-white">{new Date(event.timestamp).toLocaleString()}</div>
                    </div>
                    <div>
                        <label className="block text-gray-300 font-medium mb-1">Score</label>
                        <div className="px-3 py-2 bg-gray-800 rounded text-white">{event.confidence}%</div>
                    </div>
                    <div>
                        <label className="block text-gray-300 font-semibold mb-1 text-lg">Description</label>
                        <textarea
                            className="w-full min-h-[100px] px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-blue-500 font-medium text-base resize-vertical shadow-inner placeholder-gray-400"
                            placeholder="Add a description..."
                            value={description}
                            onChange={e => setDescription(e.target.value)}
                        />
                    </div>
                    <div>
                        <label className="block text-gray-300 font-medium mb-1">Edit Log</label>
                        <textarea
                            className="w-full min-h-[80px] px-2 py-1 rounded border border-gray-500 bg-gray-900 text-gray-200 text-xs font-mono focus:outline-none focus:ring-2 focus:ring-blue-400"
                            value={editLog.join('\n')}
                            readOnly
                        />
                    </div>
                </div>
                <div className="flex-1 flex items-center justify-center w-full">
                    <div className="w-full bg-gray-800 rounded-lg shadow-lg p-4 flex flex-col items-center">
                        <ImageEditor event={event} editLog={editLog} setEditLog={setEditLog} />
                    </div>
                </div>
            </div>
        </div>
    );
};

export default EventDetailPage;
