export const TZ = [
	{ label: 'Africa/Abidjan', value: 'Africa/Abidjan', offset: 'GMT0' },
	{ label: 'Africa/Accra', value: 'Africa/Accra', offset: 'GMT0' },
	{ label: 'Africa/Addis_Ababa', value: 'Africa/Addis_Ababa', offset: 'EAT-3' },
	{ label: 'Africa/Algiers', value: 'Africa/Algiers', offset: 'CET-1' },
	{ label: 'Africa/Asmara', value: 'Africa/Asmara', offset: 'EAT-3' },
	{ label: 'Africa/Bamako', value: 'Africa/Bamako', offset: 'GMT0' },
	{ label: 'Africa/Bangui', value: 'Africa/Bangui', offset: 'WAT-1' },
	{ label: 'Africa/Banjul', value: 'Africa/Banjul', offset: 'GMT0' },
	{ label: 'Africa/Bissau', value: 'Africa/Bissau', offset: 'GMT0' },
	{ label: 'Africa/Blantyre', value: 'Africa/Blantyre', offset: 'CAT-2' },
	{ label: 'Africa/Brazzaville', value: 'Africa/Brazzaville', offset: 'WAT-1' },
	{ label: 'Africa/Bujumbura', value: 'Africa/Bujumbura', offset: 'CAT-2' },
	{ label: 'Africa/Cairo', value: 'Africa/Cairo', offset: 'EET-2' },
	{ label: 'Africa/Casablanca', value: 'Africa/Casablanca', offset: 'WET-1' },
	{ label: 'Africa/Ceuta', value: 'Africa/Ceuta', offset: 'CET-1CEST' },
	{ label: 'Africa/Conakry', value: 'Africa/Conakry', offset: 'GMT0' },
	{ label: 'Africa/Dakar', value: 'Africa/Dakar', offset: 'GMT0' },
	{ label: 'Africa/Dar_es_Salaam', value: 'Africa/Dar_es_Salaam', offset: 'EAT-3' },
	{ label: 'Africa/Djibouti', value: 'Africa/Djibouti', offset: 'EAT-3' },
	{ label: 'Africa/Douala', value: 'Africa/Douala', offset: 'WAT-1' },
	{ label: 'Africa/El_Aaiun', value: 'Africa/El_Aaiun', offset: 'WET-1' },
	{ label: 'Africa/Freetown', value: 'Africa/Freetown', offset: 'GMT0' },
	{ label: 'Africa/Gaborone', value: 'Africa/Gaborone', offset: 'CAT-2' },
	{ label: 'Africa/Harare', value: 'Africa/Harare', offset: 'CAT-2' },
	{ label: 'Africa/Johannesburg', value: 'Africa/Johannesburg', offset: 'SAST-2' },
	{ label: 'Africa/Kampala', value: 'Africa/Kampala', offset: 'EAT-3' },
	{ label: 'Africa/Kinshasa', value: 'Africa/Kinshasa', offset: 'WAT-1' },
	{ label: 'Africa/Lagos', value: 'Africa/Lagos', offset: 'WAT-1' },
	{ label: 'Africa/Libreville', value: 'Africa/Libreville', offset: 'WAT-1' },
	{ label: 'Africa/Lome', value: 'Africa/Lome', offset: 'GMT0' },
	{ label: 'Africa/Luanda', value: 'Africa/Luanda', offset: 'WAT-1' },
	{ label: 'Africa/Lubumbashi', value: 'Africa/Lubumbashi', offset: 'CAT-2' },
	{ label: 'Africa/Lusaka', value: 'Africa/Lusaka', offset: 'CAT-2' },
	{ label: 'Africa/Malabo', value: 'Africa/Malabo', offset: 'WAT-1' },
	{ label: 'Africa/Maputo', value: 'Africa/Maputo', offset: 'CAT-2' },
	{ label: 'Africa/Maseru', value: 'Africa/Maseru', offset: 'CAT-2' },
	{ label: 'Africa/Mbabane', value: 'Africa/Mbabane', offset: 'CAT-2' },
	{ label: 'Africa/Mogadishu', value: 'Africa/Mogadishu', offset: 'EAT-3' },
	{ label: 'Africa/Monrovia', value: 'Africa/Monrovia', offset: 'GMT0' },
	{ label: 'Africa/Nairobi', value: 'Africa/Nairobi', offset: 'EAT-3' },
	{ label: 'Africa/Ndjamena', value: 'Africa/Ndjamena', offset: 'WAT-1' },
	{ label: 'Africa/Niamey', value: 'Africa/Niamey', offset: 'WAT-1' },
	{ label: 'Africa/Nouakchott', value: 'Africa/Nouakchott', offset: 'GMT0' },
	{ label: 'Africa/Ouagadougou', value: 'Africa/Ouagadougou', offset: 'GMT0' },
	{ label: 'Africa/Porto-Novo', value: 'Africa/Porto-Novo', offset: 'WAT-1' },
	{ label: 'Africa/Sao_Tome', value: 'Africa/Sao_Tome', offset: 'GMT0' },
	{ label: 'Africa/Timbuktu', value: 'Africa/Timbuktu', offset: 'GMT0' },
	{ label: 'Africa/Tunis', value: 'Africa/Tunis', offset: 'CET-1' },
	{ label: 'Africa/Windhoek', value: 'Africa/Windhoek', offset: 'CAT-2' },
	{ label: "Etc/GMT", value: "Etc/GMT", offset: "GMT0" },
	{ label: "Etc/GMT+1", value: "Etc/GMT+1", offset: "<-01>1" },
	{ label: "Etc/GMT+10", value: "Etc/GMT+10", offset: "<-10>10" },
	{ label: "Etc/GMT+11", value: "Etc/GMT+11", offset: "<-11>11" },
	{ label: "Etc/GMT+12", value: "Etc/GMT+12", offset: "<-12>12" },
	{ label: "Etc/GMT+2", value: "Etc/GMT+2", offset: "<-02>2" },
	{ label: "Etc/GMT+3", value: "Etc/GMT+3", offset: "<-03>3" },
	{ label: "Etc/GMT+4", value: "Etc/GMT+4", offset: "<-04>4" },
	{ label: "Etc/GMT+5", value: "Etc/GMT+5", offset: "<-05>5" },
	{ label: "Etc/GMT+6", value: "Etc/GMT+6", offset: "<-06>6" },
	{ label: "Etc/GMT+7", value: "Etc/GMT+7", offset: "<-07>7" },
	{ label: "Etc/GMT+8", value: "Etc/GMT+8", offset: "<-08>8" },
	{ label: "Etc/GMT+9", value: "Etc/GMT+9", offset: "<-09>9" },
	{ label: "Etc/GMT-1", value: "Etc/GMT-1", offset: "<+01>-1" },
	{ label: "Etc/GMT-10", value: "Etc/GMT-10", offset: "<+10>-10" },
	{ label: "Etc/GMT-11", value: "Etc/GMT-11", offset: "<+11>-11" },
	{ label: "Etc/GMT-12", value: "Etc/GMT-12", offset: "<+12>-12" },
	{ label: "Etc/GMT-13", value: "Etc/GMT-13", offset: "<+13>-13" },
	{ label: "Etc/GMT-14", value: "Etc/GMT-14", offset: "<+14>-14" },
	{ label: "Etc/GMT-2", value: "Etc/GMT-2", offset: "<+02>-2" },
	{ label: "Etc/GMT-3", value: "Etc/GMT-3", offset: "<+03>-3" },
	{ label: "Etc/GMT-4", value: "Etc/GMT-4", offset: "<+04>-4" },
	{ label: "Etc/GMT-5", value: "Etc/GMT-5", offset: "<+05>-5" },
	{ label: "Etc/GMT-6", value: "Etc/GMT-6", offset: "<+06>-6" },
	{ label: "Etc/GMT-7", value: "Etc/GMT-7", offset: "<+07>-7" },
	{ label: "Etc/GMT-8", value: "Etc/GMT-8", offset: "<+08>-8" },
	{ label: "Etc/GMT-9", value: "Etc/GMT-9", offset: "<+09>-9" },

	{ label: "Europe/Astrakhan", value: "Europe/Astrakhan", offset: "<+04>-4" },


	{ label: "Europe/Berlin", value: "Europe/Berlin", offset: "CET-1" },


	{ label: "Europe/Chisinau", value: "Europe/Chisinau", offset: "EET-2" },

	{ label: "Europe/Dublin", value: "Europe/Dublin", offset: "IST-1" },
	{ label: "Europe/London", value: "Europe/London", offset: "GMT0" },

	{ label: "Europe/Moscow", value: "Europe/Moscow", offset: "MSK-3" },



]
